#!/bin/bash
# This Script by ALK-NET

id=$(usbreset | grep ID | cut -d' ' -f7)
prod=$(usbreset | grep ID | cut -d' ' -f9)
bug=$1
tgl=$(date)
dc=$(httping -c 1 ${bug} | grep connected | cut -d= -f3 | grep -c ms)

if [[ $dc = "1" ]]; then
   echo -e "Connected"
else
   echo -e "No Internet"
   echo -e "Mereset Koneksi USB Modem : "$prod
   logger "Mereset Koneksi USB Modem : "$prod
   sleep 3
   usbreset $id
fi	

